Fix typo

diff --git a/generic-script b/generic-script
--- a/generic-script
+++ b/generic-script
@@ -161,8 +161,8 @@ get_params()
 
 generic_script_monitor()
 {
-	echo "`date` Start monitoring: POOP and $SCRIPT and $STARTARG and $STOPARG and $ARGS and $OCF_RESKEY_state" >> /tmp/monitor.txt
-	echo "`date` Start monitoring: POOP and $SCRIPT and $STARTARG and $STOPARG and $ARGS and $OCF_RESKEY_state" >> /tmp/start.txt
+	echo "`date` Start monitoring $SCRIPT" >> /tmp/monitor.txt
+	echo "`date` Start monitoring $SCRIPT" >> /tmp/start.txt
 
 	if [ -f ${OCF_RESKEY_state} ]; then
 		echo "Exec monitoring script: $SCRIPT" >> /tmp/monitor.txt
@@ -170,7 +170,6 @@ generic_script_monitor()
 		if [ -n ${ALWAYSRUN} ]; then
 			$($SCRIPT $ARGS >/dev/null 2>&1)
 			if [ $? -ne 0 ]; then
-				#echo "SHIT FUCK IT FAILED" >> /tmp/monitor.txt
 				ocf_log err "Error. $OCF_RESKEY_name script returned error $?."
 				return $OCF_ERR_GENERIC
 			fi
@@ -186,7 +185,7 @@ generic_script_monitor()
 
 generic_script_start()
 {
-	echo "Process start script" >> /tmp/start.txt
+	echo "`date` Process start script with input: COMMAND - $COMMAND : " >> /tmp/start.txt
 	# check if the script is there
 	if [ -x "$SCRIPT" ]; then
 		COMMAND=$SCRIPT
@@ -198,9 +197,9 @@ generic_script_start()
 	generic_script_monitor
 	retVal=$?
 	if [ $retVal -eq $OCF_NOT_RUNNING ]; then
-		echo "`date` 2) Going to do $COMMAND $STARTARGS" >> /tmp/start.txt
-		$($COMMAND $STARTARGS >/dev/null 2>&1)
-		echo "`date` Started script $COMMAND $STARTARGS" >> /tmp/start.txt
+		echo "`date` 2) Going to do $COMMAND $STARTARG" >> /tmp/start.txt
+		$($COMMAND $STARTARG >/dev/null 2>&1)
+		echo "`date` Started script $COMMAND $STARTARG" >> /tmp/start.txt
 		if [ $? -ne 0 ]; then
 			ocf_log err "Error. $OCF_RESKEY_name script returned error $?."
 			exit $OCF_ERR_GENERIC
@@ -226,47 +225,41 @@ generic_script_start()
 
 generic_script_stop()
 {
+	echo "`date` Service stopped" >> /tmp/start.txt
+	# check if the script is there
+	if [ -x "$SCRIPT" ]; then
+		COMMAND=$SCRIPT
+	else
+		ocf_log err "Error. Script is not executable."
+		exit $OCF_ERR_GENERIC
+	fi
+
 	generic_script_monitor
-    if [ $? =  $OCF_SUCCESS ]; then
-		rm ${OCF_RESKEY_state}
-    fi
-	return $OCF_SUCCESS
+	retVal=$?
+	if [ $retVal -eq $OCF_SUCCESS ]; then
+		echo "`date` 2) Going to do stop script" >> /tmp/start.txt
+		# If both of these are not present, we're not supposed to run
+		if [[ -z $STARTANDSTOP && -z $STOPARG ]]; then
+			rm -f ${OCF_RESKEY_state}
+			exit $OCF_SUCCESS
+		fi
+		$($COMMAND ${STOPARG} >/dev/null 2>&1)
+		echo "STOP $COMMAND ${STOPARG}"" >>/tmp/stop.txt
+		if [ $? -ne 0 ]; then
+			ocf_log err "Error. $OCF_RESKEY_name script returned error $?."
+			exit $OCF_ERR_GENERIC
+		else
+			rm -f ${OCF_RESKEY_state}
+			ocf_log info "Executed $OCF_RESKEY_name script in the START mode."
+			exit $OCF_SUCCESS
+		fi
 
-	# echo "`date` Service stopped" >> /tmp/start.txt
-	# # check if the script is there
-	# if [ -x "$SCRIPT" ]; then
-	# 	COMMAND=$SCRIPT
-	# else
-	# 	ocf_log err "Error. Script is not executable."
-	# 	exit $OCF_ERR_GENERIC
-	# fi
-
-	# generic_script_monitor
-	# retVal=$?
-	# if [ $retVal -eq $OCF_SUCCESS ]; then
-	# 	echo "`date` 2) Going to do stop script" >> /tmp/start.txt
-	# 	# If both of these are not present, we're not supposed to run
-	# 	if [[ -z $STARTANDSTOP && -z $STOPARG ]]; then
-	# 		rm -f ${OCF_RESKEY_state}
-	# 		exit $OCF_SUCCESS
-	# 	fi
-	# 	$($COMMAND ${STOPARGS:-$ARGS} >/dev/null 2>&1)
-	# 	#echo STOP $COMMAND ${STOPARGS:-$ARGS} >>/tmp/stop.txt
-	# 	if [ $? -ne 0 ]; then
-	# 		ocf_log err "Error. $OCF_RESKEY_name script returned error $?."
-	# 		exit $OCF_ERR_GENERIC
-	# 	else
-	# 		rm -f ${OCF_RESKEY_state}
-	# 		ocf_log info "Executed $OCF_RESKEY_name script in the START mode."
-	# 		exit $OCF_SUCCESS
-	# 	fi
-
-	# elif [ $retVal -eq $OCF_NOT_RUNNING ]; then
-	# 	exit $OCF_SUCCESS
-	# else
-	# 	ocf_log err "$SCRIPT monitor is neither running or stopped,exiting."
-	# 	exit $OCF_ERR_GENERIC
-	# fi
+	elif [ $retVal -eq $OCF_NOT_RUNNING ]; then
+		exit $OCF_SUCCESS
+	else
+		ocf_log err "$SCRIPT monitor is neither running or stopped,exiting."
+		exit $OCF_ERR_GENERIC
+	fi
 
 }
 
